### ISSUE TITLE
LDPartEditor should be wrapped in an executable with Launch4j.

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#656]
### TODO
- [x] Windows executable (created by an ANT task -> no additional overhead!)
- [x] Windows setup file (created with InnoSetup).
- [x] LDPE should store the config and...
- [x] Logfiles and the...
- [x] Temporary project files in an AppData folder under Windows.

### New folder structure with exe:
![withexe](https://user-images.githubusercontent.com/11047164/34649343-9fe969f0-f3ad-11e7-8598-4df03cd36be7.PNG)

### Old folder structure without exe:
![withoutexe](https://user-images.githubusercontent.com/11047164/34649346-b1fa3bb0-f3ad-11e7-9553-10448ddc1ac5.PNG)

_____________________
Backup of my current l4j installation on Linux (x64):
[launch4j.zip](https://github.com/nilsschmidt1337/ldparteditor/files/1609726/launch4j.zip)

**Comment by nilsschmidt1337** [comment]
Closed with commit 1079897
