### ISSUE TITLE
As a user I want to use the !DATA meta command.

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#980]
**Syntax:**
```
!DATA
Format: 0 !DATA <filename>
Where:
<filename> is the filename of the following encoded data.

Blocks starting with the 0 !DATA statement contain binary data encoded using a multitude of 0 !: lines.
Each of those lines contain a chunk of base64 encoded data which a parser must combine before decoding. 
No other LDraw statements may be used inside a !DATA block.
```

- [x] The user should be able to export the !DATA only as png
- [x] The user should be able to create the !DATA meta command (205 characters per line, 5 chars to start, 200 chars for the encoded data)
- [x] Strong protection against malicious files or PNGs (prevent the export of this data / [Malicious PNGs What You See Is Not All You Get!.pdf](https://github.com/nilsschmidt1337/ldparteditor/files/12472752/Malicious.PNGs.What.You.See.Is.Not.All.You.Get.pdf))

**PNG-Standard:**
https://en.wikipedia.org/wiki/PNG
**Base-64-Standard:**
https://datatracker.ietf.org/doc/html/rfc4648#section-4

**Example:**
```
0 Testcase
0 Name: new.dat
0 Author: Nils Schmidt [BlackBrick89]
0 !LDRAW_ORG Unofficial_Part
0 !LICENSE Licensed under CC BY 2.0 and CC BY 4.0 : see CAreadme.txt

0 BFC CERTIFY CCW

0 !DATA sticker.png
0 !: iVBORw0KGgoAAAANSUhEUgAAAFAAAAB4CAIAAADqjOKhAAAAAXNSR0IArs4c6QAAAARnQU1BAACx
0 !: jwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAEUSURBVHhe7du9DcIwFABhk5WgQLSsQM0UjMEU
0 !: 1BQsQIsoYAt6NkAYxQV/JQ7WvfuKkFTR6UmOFJzR9bJLkXTlNwyD6QymM5ju5Tl8m67KGUt3XJcz
0 !: J/yY8HZ/6C8BFvNZPoaesMF0BtMZTGcwncF0BtMZTGcwncF0BtMZTGcwnf8t0bmLh85gOoPpDKYz
0 !: mM5gOoPpDKYzmM5gunDBf3tN+/zqNKt367cbOeGUTstxf1nJZHPOx68T/u3XB5/7/zMXLTqD6Qym
0 !: M5jOYDqD6QymM5jOYDqD6QymM5jOYDqD6QymM5jOYLpwwW3t8ajBXTxtTHgwLlp0BtMZTGcwncF0
0 !: BtMZTNfKZzyDiT3hCFy06IIFp3QH/CBMh66aBy4AAAAASUVORK5CYII=

0 !TEXMAP START PLANAR 0 0 0 10 0 0 0 10 0 sticker.png
0 !: 4 16 0 0 0 10 0 0 10 10 0 0 10 0
0 !TEXMAP FALLBACK
4 16 0 0 0 10 0 0 10 10 0 0 10 0
0 !TEXMAP END
```

**Comment by nilsschmidt1337** [comment]
Closed with commit [fe40235](https://github.com/nilsschmidt1337/ldparteditor/commit/fe40235bf8974589af893aa4656cecfd7ae14973).
